# Retrieve only the adjacency matrices from an object generated by the CVNSim package
get_just_adj_matrices <- function(truth) {
  # Use lapply to extract the 'adj_matrix' component from each graph in the 'truth' list
  lapply(truth, function(graph) graph$adj_matrix)
}

